### ISSUE TITLE
[BUG] Speed Troubles

### ISSUE THREAD

**Issue by EnderGirl1500** [Picono435/RandomTP#13]
**Describe the bug**
I'm having lag issues. On my singleplayer world works fine, but when I added the mod on my server it went so laggy, it's impossible to play like that. The issue comes when anyone uses the /rtp command. After being teleported, the lag stops. My server has 6GB of RAM, maybe that could be the issue, but before adding RAM to the server I prefer consulting this here.

**Desktop (please complete the following information):**
 - RandomTP version: last version
 - Minecraft Version: 1.18.2 fabric

**Comment by Picono435** [comment]
I am aware of this issue and I am now working on a fix. Thank you for contacting me :).

**Comment by Picono435** [comment]
In order to help fixing the lag on servers I highly recommend you to set a max-tries value.

**Comment by EnderGirl1500** [comment]
Can you explain me a bit how the max-tries thing works or which amount could be good?

**Comment by Picono435** [comment]
In order to find a safe place to teleport to the mod will execute a loop finding random locations (which is the thing that lags the server). By default, this loop will run infinitely if you set max tries to for example 1000 it will only run 1000 times. You can try to set it to 1000 and see if it still lags the server if it does try to lower it down a bit. Keep in mind that if the value is small the chance of finding a teleport location will be smaller.

**Comment by EnderGirl1500** [comment]
Oh ok. Thanks a lot! I'll try that later and tell you if it worked.

**Comment by Picono435** [comment]
This issue was fixed in the latest commit.
