### ISSUE TITLE
[BUG] Some players when they write /rtp then end up outside the world and die

### ISSUE THREAD

**Issue by GitJhopa** [Picono435/RandomTP#30]
Some players when they write /rtp then end up outside the world and die, my config is below.

Forge 1.19.2
Config mod: https://pastebin.com/aZebuvLm
Mod version: randomtp-7.1.0+1.19-forge.jar

**Comment by Picono435** [comment]
"My world border is /worldborder set to 10000, how does the player end up at 5300 coordinates?"

**Comment by GitJhopa** [comment]
yes

**Comment by shinji257** [comment]
We are getting reports of players getting shot outside of world border as well.

Configuration - min 1000, max 10000
World border size 25000 (so 12500 in each direction from 0)

I should additionally mention that I'm on 1.18.2 just in case it matters but I see fixes in newer versions were brought back.
It might not have improved it enough though.  Currently the "fix" will be to set `use-original` to false to it uses spreadplayers instead of the new system.

**Comment by Picono435** [comment]
Yeah this is not expected and 1.18.2 is still a supported version I will look into it. For now if you want to use the original system you can try and set max-distance to 0 and see if it works.

**Comment by Picono435** [comment]
This has been fixed in the latest release.
